feat: group sections to chapters
ahmadrosid/learnwise pull request #28
Opened 2023-11-10 16:58 UTC by caesar003

do

```sh
php artisan migrate
```

where to look:

```
chapter edit: `/teacher/chapter/edit/{chapter}
```

```
chapter display: `courses/{slug}/chapter/{chapter}`

2023-11-14 23:18 UTC, caesar003 commented
do the following,
```sh
php artisan migrate
```

2023-11-15 04:05 UTC, ahmadrosid commented on resources/views/teachers/course/setup.blade.php
> +                                                                    value={{ $course->id }} />
Wrap in a string please `"{{ $course->id }}"`

2023-11-15 04:09 UTC, ahmadrosid requested changes
Got this error when opening detail course: http://localhost:8000/course/introduction-to-psychology

<img width="1143" alt="Screenshot 2023-11-15 at 11 08 25" src="https://github.com/ahmadrosid/learnwise/assets/29406408/c67ae7c1-ff49-4a8d-aed5-7c5644df66a9">

2023-11-15 05:54 UTC, ahmadrosid commented on resources/views/courses/index.blade.php
> +                                                                    class="btn">preview</button></span>
highlight the preview button using underline.

<img width="811" alt="Screenshot 2023-11-15 at 12 53 48" src="https://github.com/ahmadrosid/learnwise/assets/29406408/970acf92-3ecc-4901-bdc1-282cce436e1d">

2023-11-15 05:54 UTC, ahmadrosid commented on resources/views/courses/index.blade.php
> +                                                        <span>{{ $ch->video_duration ? secondsToHMS($ch->video_duration) : '-' }}</span>
use empty string when the chapters doesn't have duration

2023-11-15 05:57 UTC, ahmadrosid commented on resources/js/app.js
> +}
Run this on the backend side instead, because we might limit the API using apikey someday.

2023-11-15 05:59 UTC, ahmadrosid commented on resources/views/courses/index.blade.php
> +                                                        <span>{{ $ch->video_duration ? secondsToHMS($ch->video_duration) : '-' }}</span>
and add space in the end of duration
![Uploading Screenshot 2023-11-15 at 12.58.42.png…]()

2023-11-15 05:59 UTC, ahmadrosid commented on resources/views/courses/index.blade.php
> +                                    </div>
same here the spacing

2023-11-15 06:01 UTC, ahmadrosid commented on resources/views/courses/index.blade.php
> +                    </div>
get the data from DB.

2023-11-15 06:02 UTC, ahmadrosid commented on app/Http/Controllers/CourseController.php
> +        // dd($chapters);
clean up this unused code

2023-11-15 06:02 UTC, ahmadrosid commented on app/Http/Controllers/ReviewController.php
> +}
we don't need this at the moment so you delete it.

2023-11-15 06:03 UTC, ahmadrosid commented on app/Models/Review.php
> +class Review extends Model
same here

2023-11-15 06:03 UTC, ahmadrosid commented on database/migrations/2023_11_13_140950_create_reviews_table.php
> +        Schema::create('reviews', function (Blueprint $table) {
here too

2023-11-15 06:04 UTC, ahmadrosid commented on resources/js/app.js
> +    // });
remove this debug code

2023-11-15 06:06 UTC, ahmadrosid commented on resources/js/app.js
> +function createAccordion(sections, videoId) {
no need to setup accordion in the dialog play free chapters.

2023-11-18 17:58 UTC, ahmadrosid approved these changes

2023-11-18 17:58 UTC, merged